spring:
# 配置rabbitMQspring:
  rabbitmq:
    host: 120.78.170.24
    port: 5672
    username: guest
    password: guest
    virtual-host: spring-boot-vhost
  application:
    name: hero-feign


  datasource :
      url : jdbc:mysql://120.78.170.24:3306/test
      username : root
      password : root
      driver-class-name : com.mysql.jdbc.Driver
  redis.database : 0
  redis.host : 120.78.170.24
  redis.port : 6379
  redis.password : 103021
  redis.pool.max-total : 8
  redis.pool.max-wait : -1
  redis.pool.max-idle : 8
  redis.pool.min-idle : 0
  redis.pool.timeout : 10000


logging.level.com.hero.feign.IUserFeignClient: DEBUG
mybatis.mapper-locations : classpath:mappers/*.xml
server.port : 8083

eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:1111/eureka

  # 显示ip地址  不写就显示主机名称
  instance:
    prefer-ip-address : true
    instance-id: ${spring.application.name}
#    appname:


#hystrix.command.default.execution.isolation.thread.timeoutInMillseconds: 5000

# 值为false时，禁用feign对hystrix 的支持
feign.hystrix.enabled: true

#微服务间调用其实走的是http请求，debug了一下默认的ReadTimeout时间为5s，ConnectTimeout时间为2s，
#Fegin进行微服务间调用，底层用的还是Ribbon。
# 设置读取超时时间
ribbon.ReadTimeout: 6000
# 设置连接超时时间
ribbon.ConnectTimeout: 600
# 对所有操作请求都进行重试
ribbon.OkToRetryOnAllOperations: true
# 对当前实例的重试次数
ribbon.MaxAutoRetries: 0
# 切换实例的重试次数
ribbon.MaxAutoRetriesNextServer: 1

