spring:
  application:
    name: hero-feign

  datasource :
      url : jdbc:mysql://192.168.71.35:3306/test
      username : root
      password : 123456
      driver-class-name : com.mysql.jdbc.Driver
  redis.database : 0
  redis.host : 192.168.71.36
  redis.port : 6379
  redis.password : 123456
  redis.pool.max-total : 8
  redis.pool.max-wait : -1
  redis.pool.max-idle : 8
  redis.pool.min-idle : 0
  redis.pool.timeout : 10000


logging.level.com.hero.feign.IUserFeignClient: DEBUG
mybatis.mapper-locations : classpath:mappers/*.xml
server.port : 8083

eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:1111/eureka

  # 显示ip地址  不写就显示主机名称
  instance:
    prefer-ip-address : true
    instance-id: ${spring.application.name}


#hystrix.command.default.execution.isolation.thread.timeoutInMillseconds: 5000


#微服务间调用其实走的是http请求，debug了一下默认的ReadTimeout时间为5s，ConnectTimeout时间为2s，
#Fegin进行微服务间调用，底层用的还是Ribbon。
ribbon.ReadTimeout: 60000
ribbon.ConnectTimeout: 60000
ribbon.MaxAutoRetries: 0
ribbon.MaxAutoRetriesNextServer: 1